apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: myapp
  name: myapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - image: myapp:latest
          imagePullPolicy: Always
          name: myapp
          ports:
          - containerPort: 8080
            protocol: TCP
  selector:
    app: myapp
  strategy:
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  triggers:
  - type: ConfigChange
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
      - myapp
      from:
        kind: ImageStreamTag
        name: myapp:latest
