apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    type: echo
spec:
  containers:
    - name: mycontainer
      image: lulf/openshift-echo:latest
      ports:
        - name: echo
          containerPort: 2000
