apiVersion: v1
kind: ReplicationController
metadata:
  name: mycontroller
spec:
  replicas: 3
  template:
    metadata:
      labels:
        type: echo
    spec:
      containers:
        - name: mypod
          image: lulf/openshift-echo:latest
          ports:
            - name: echo
              containerPort: 2000
